../bin/gradexor.elf sanko
../bin/gradexor.elf hello
../bin/gradexor.elf waves
../bin/gradexor.elf boxes
../bin/gradexor.elf lines
../bin/gradexor.elf scale
../bin/gradexor.elf types
../bin/gradexor.elf typed
../bin/gradexor.elf typer
